[package]
name = "random"
author = "Shresht7"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "random"
src = "src/main.rs"

[lib]
name = "random"
path = "src/lib/mod.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
is-terminal = "0.4.9"
rand = "0.8.5"
