[package]
name = "random"
author = "Shresht7"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "random"
src = "src/main.rs"

[lib]
name = "lib"
path = "src/lib/mod.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
clap = { version = "4.4.7", features = ["derive"] }
rand = "0.8.5"
